<a href="https://colab.research.google.com/github/ASB0M/PythonPractice/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.2.3

Series

a pandas 1-dimentional labbeled array that can hold any datatype.
think of it like a single column in a spreadsheet

In [4]:
data = [100,102,104,200,202]

In [5]:
series = pd.Series(data, index = ["a", "b", "c","d", "e"]) #Series() = series cunstructor
print(series)

a    100
b    102
c    104
d    200
e    202
dtype: int64

In [6]:
print(series.loc["a"]) # to access location by label

100

In [7]:
series.loc["c"] = 200
print(series)

a    100
b    102
c    200
d    200
e    202
dtype: int64

In [8]:
print(series.iloc[0]) # to access location by integer

100

In [9]:
print(series[series >=200 ])

c    200
d    200
e    202
dtype: int64

In [10]:
calories = {'Day 1': 1400, "Day 2":2100, "Day 3":1200}

In [11]:
series = pd.Series(calories)

In [12]:
print(series[series > 1500])

Day 2    2100
dtype: int64

Dataframes

Tabular data sturcture with rows and caulmns. 2-dimentional similer to excell sheet

In [13]:
data = {"Name":["Asad", "Saqib", "Sabih", "Ahmed"],
        "Age": [21, 41, 26, 30]}

In [14]:
df = pd.DataFrame(data, index = ["emp 1", "emp 2", "emp 3", "emp 4"]) # DataFrame() -- cunstructor

In [15]:
print(df)

        Name  Age
emp 1   Asad   21
emp 2  Saqib   41
emp 3  Sabih   26
emp 4  Ahmed   30

In [16]:
print(df.loc["emp 1"])

Name    Asad
Age       21
Name: emp 1, dtype: object

In [17]:
# new caulmn

df["Job"] = ["data scientist", "finance head", "CEO", "marcom"]

In [18]:
print(df)

        Name  Age             Job
emp 1   Asad   21  data scientist
emp 2  Saqib   41    finance head
emp 3  Sabih   26             CEO
emp 4  Ahmed   30          marcom

In [19]:
# new row

new_row = pd.DataFrame([{"Name": "Ali", "Age": 32, "Job": "intern"}], index = ["emp 5"]) # passing in alist of dictionaries each for a new row

In [20]:
df = pd.concat([df, new_row])
print(df)

        Name  Age             Job
emp 1   Asad   21  data scientist
emp 2  Saqib   41    finance head
emp 3  Sabih   26             CEO
emp 4  Ahmed   30          marcom
emp 5    Ali   32          intern

In [37]:
import kagglehub
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

Using Colab cache for faster access to the 'students-performance-in-exams' dataset.

In [38]:
import os

data = pd.read_csv(os.path.join(path, "StudentsPerformance.csv"), index_col = "gender")

In [39]:
data.head()

,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
gender,,,,,,,
female,group B,bachelor's degree,standard,none,72,72,74
female,group C,some college,standard,completed,69,90,88
female,group B,master's degree,standard,none,90,95,93
male,group A,associate's degree,free/reduced,none,47,57,44
male,group C,some college,standard,none,76,78,75

In [40]:
print(data.to_string())

       race/ethnicity parental level of education         lunch test preparation course  math score  reading score  writing score
gender
female        group B           bachelor's degree      standard                    none          72             72             74
female        group C                some college      standard               completed          69             90             88
female        group B             master's degree      standard                    none          90             95             93
male          group A          associate's degree  free/reduced                    none          47             57             44
male          group C                some college      standard                    none          76             78             75
female        group B          associate's degree      standard                    none          71             83             78
female        group B                some college      standard               completed          88             95             92
male          group B                some college  free/reduced                    none          40             43             39
male          group D                 high school  free/reduced               completed          64             64             67
female        group B                 high school  free/reduced                    none          38             60             50
male          group C          associate's degree      standard                    none          58             54             52
male          group D          associate's degree      standard                    none          40             52             43
female        group B                 high school      standard                    none          65             81             73
male          group A                some college      standard               completed          78             72             70
female        group A             master's degree      standard                    none          50             53             58
female        group C            some high school      standard                    none          69             75             78
male          group C                 high school      standard                    none          88             89             86
female        group B            some high school  free/reduced                    none          18             32             28
male          group C             master's degree  free/reduced               completed          46             42             46
female        group C          associate's degree  free/reduced                    none          54             58             61
male          group D                 high school      standard                    none          66             69             63
female        group B                some college  free/reduced               completed          65             75             70
male          group D                some college      standard                    none          44             54             53
female        group C            some high school      standard                    none          69             73             73
male          group D           bachelor's degree  free/reduced               completed          74             71             80
male          group A             master's degree  free/reduced                    none          73             74             72
male          group B                some college      standard                    none          69             54             55
female        group C           bachelor's degree      standard                    none          67             69             75
male          group C                 high school      standard                    none          70             70             65
female        group D             master's degree      standard                    none          62             70             75
female        group D                some college      standard                    none          69             74             74
female        group B                some college      standard                    none          63             65             61
female        group E             master's degree  free/reduced                    none          56             72             65
male          group D                some college      standard                    none          40             42             38
male          group E                some college      standard                    none          97             87             82
male          group E          associate's degree      standard               completed          81             81             79
female        group D          associate's degree      standard                    none          74             81             83
female        group D            some high school  free/reduced                    none          50             64             59
female        group D          associate's degree  free/reduced               completed          75             90             88
male          group B          associate's degree  free/reduced                    none          57             56             57
male          group C          associate's degree  free/reduced                    none          55             61             54
female        group C          associate's degree      standard                    none          58             73             68
female        group B          associate's degree      standard                    none          53             58             65
male          group B                some college  free/reduced               completed          59             65             66
female        group E          associate's degree  free/reduced                    none          50             56             54
male          group B          associate's degree      standard                    none          65             54             57
female        group A          associate's degree      standard               completed          55             65             62
female        group C                 high school      standard                    none          66             71             76
female        group D          associate's degree  free/reduced               completed          57             74             76
male          group C                 high school      standard               completed          82             84             82
male          group E                some college      standard                    none          53             55             48
male          group E          associate's degree  free/reduced               completed          77             69             68
male          group C                some college      standard                    none          53             44             42
male          group D                 high school      standard                    none          88             78             75
female        group C            some high school  free/reduced               completed          71             84             87
female        group C                 high school  free/reduced                    none          33             41             43
female        group E          associate's degree      standard               completed          82             85             86
male          group D          associate's degree      standard                    none          52             55             49
male          group D                some college      standard               completed          58             59             58
female        group C            some high school  free/reduced                    none           0             17             10
male          group E           bachelor's degree  free/reduced               completed          79             74             72
male          group A            some high school  free/reduced                    none          39             39             34
male          group A          associate's degree  free/reduced                    none          62             61             55
female        group C          associate's degree      standard                    none          69             80             71
female        group D            some high school      standard                    none          59             58             59
male          group B            some high school      standard                    none          67             64             61
male          group D            some high school  free/reduced                    none          45             37             37
female        group C                some college      standard                    none          60             72             74
male          group B          associate's degree  free/reduced                    none          61             58             56
female        group C          associate's degree      standard                    none          39             64             57
female        group D                some college  free/reduced               completed          58             63             73
male          group D                some college      standard               completed          63             55             63
female        group A          associate's degree  free/reduced                    none          41             51             48
male          group C            some high school  free/reduced                    none          61             57             56
male          group C            some high school      standard                    none          49             49             41
male          group B          associate's degree  free/reduced                    none          44             41             38
male          group E            some high school      standard                    none          30             26             22
male          group A           bachelor's degree      standard               completed          80             78             81
female        group D            some high school      standard               completed          61             74             72
female        group E             master's degree      standard                    none          62             68             68
female        group B          associate's degree      standard                    none          47             49             50
male          group B                 high school  free/reduced                    none          49             45             45
male          group A                some college  free/reduced               completed          50             47             54
male          group E          associate's degree      standard                    none          72             64             63
male          group D                 high school  free/reduced                    none          42             39             34
female        group C                some college      standard                    none          73             80             82
female        group C                some college  free/reduced                    none          76             83             88
female        group D          associate's degree      standard                    none          71             71             74
female        group A                some college      standard                    none          58             70             67
female        group D            some high school      standard                    none          73             86             82
female        group C           bachelor's degree      standard                    none          65             72             74
male          group C                 high school  free/reduced                    none          27             34             36
male          group C                 high school      standard                    none          71             79             71
male          group C          associate's degree  free/reduced               completed          43             45             50
female        group B                some college      standard                    none          79             86             92
male          group C          associate's degree  free/reduced               completed          78             81             82
male          group B            some high school      standard               completed          65             66             62
female        group E                some college      standard               completed          63             72             70
female        group D                some college  free/reduced                    none          58             67             62
female        group D           bachelor's degree      standard                    none          65             67             62
male          group B                some college      standard                    none          79             67             67
male          group D           bachelor's degree      standard               completed          68             74             74
female        group D          associate's degree      standard                    none          85             91             89
male          group B                 high school      standard               completed          60             44             47
male          group C                some college      standard               completed          98             86             90
female        group C                some college      standard                    none          58             67             72
female        group D             master's degree      standard                    none          87            100            100
male          group E          associate's degree      standard               completed          66             63             64
female        group B          associate's degree  free/reduced                    none          52             76             70
female        group B            some high school      standard                    none          70             64             72
female        group D          associate's degree  free/reduced               completed          77             89             98
male          group C                 high school      standard                    none          62             55             49
male          group A          associate's degree      standard                    none          54             53             47
female        group D                some college      standard                    none          51             58             54
female        group E           bachelor's degree      standard               completed          99            100            100
male          group C                 high school      standard                    none          84             77             74
female        group B           bachelor's degree  free/reduced                    none          75             85             82
female        group D           bachelor's degree      standard                    none          78             82             79
female        group D            some high school      standard                    none          51             63             61
female        group C                some college      standard                    none          55             69             65
female        group C           bachelor's degree      standard               completed          79             92             89
male          group B          associate's degree      standard               completed          91             89             92
female        group C                some college      standard               completed          88             93             93
male          group D                 high school  free/reduced                    none          63             57             56
male          group E                some college      standard                    none          83             80             73
female        group B                 high school      standard                    none          87             95             86
male          group B            some high school      standard                    none          72             68             67
male          group D                some college      standard               completed          65             77             74
male          group D             master's degree      standard                    none          82             82             74
female        group A           bachelor's degree      standard                    none          51             49             51
male          group D             master's degree      standard                    none          89             84             82
male          group C            some high school  free/reduced               completed          53             37             40
male          group E                some college  free/reduced               completed          87             74             70
female        group C                some college      standard               completed          75             81             84
male          group D           bachelor's degree  free/reduced               completed          74             79             75
male          group C           bachelor's degree      standard                    none          58             55             48
male          group B            some high school      standard               completed          51             54             41
male          group E                 high school      standard                    none          70             55             56
female        group C          associate's degree      standard                    none          59             66             67
male          group D                some college      standard               completed          71             61             69
female        group D            some high school      standard                    none          76             72             71
female        group C                some college  free/reduced                    none          59             62             64
female        group E                some college  free/reduced               completed          42             55             54
male          group A                 high school      standard                    none          57             43             47
male          group D                some college      standard                    none          88             73             78
female        group C                some college  free/reduced                    none          22             39             33
male          group B            some high school      standard                    none          88             84             75
male          group C          associate's degree  free/reduced                    none          73             68             66
female        group D           bachelor's degree      standard               completed          68             75             81
male          group E          associate's degree  free/reduced               completed         100            100             93
male          group A            some high school      standard               completed          62             67             69
male          group A           bachelor's degree      standard                    none          77             67             68

In [41]:
# Importing JSON (Java Script Object Notation)

path = "/content/sample_data/anscombe.json"
dataJSON = pd.read_json(os.path.join(path, "anscombe.json"))

FileNotFoundError: File /content/sample_data/anscombe.json/anscombe.json does not exist

Selection

In [42]:
data.head()

,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
gender,,,,,,,
female,group B,bachelor's degree,standard,none,72,72,74
female,group C,some college,standard,completed,69,90,88
female,group B,master's degree,standard,none,90,95,93
male,group A,associate's degree,free/reduced,none,47,57,44
male,group C,some college,standard,none,76,78,75

In [43]:
# selection by caulmn

print(data["race/ethnicity"].to_string())

gender
female    group B
female    group C
female    group B
male      group A
male      group C
female    group B
female    group B
male      group B
male      group D
female    group B
male      group C
male      group D
female    group B
male      group A
female    group A
female    group C
male      group C
female    group B
male      group C
female    group C
male      group D
female    group B
male      group D
female    group C
male      group D
male      group A
male      group B
female    group C
male      group C
female    group D
female    group D
female    group B
female    group E
male      group D
male      group E
male      group E
female    group D
female    group D
female    group D
male      group B
male      group C
female    group C
female    group B
male      group B
female    group E
male      group B
female    group A
female    group C
female    group D
male      group C
male      group E
male      group E
male      group C
male      group D
female    group C
female    group C
female    group E
male      group D
male      group D
female    group C
male      group E
male      group A
male      group A
female    group C
female    group D
male      group B
male      group D
female    group C
male      group B
female    group C
female    group D
male      group D
female    group A
male      group C
male      group C
male      group B
male      group E
male      group A
female    group D
female    group E
female    group B
male      group B
male      group A
male      group E
male      group D
female    group C
female    group C
female    group D
female    group A
female    group D
female    group C
male      group C
male      group C
male      group C
female    group B
male      group C
male      group B
female    group E
female    group D
female    group D
male      group B
male      group D
female    group D
male      group B
male      group C
female    group C
female    group D
male      group E
female    group B
female    group B
female    group D
male      group C
male      group A
female    group D
female    group E
male      group C
female    group B
female    group D
female    group D
female    group C
female    group C
male      group B
female    group C
male      group D
male      group E
female    group B
male      group B
male      group D
male      group D
female    group A
male      group D
male      group C
male      group E
female    group C
male      group D
male      group C
male      group B
male      group E
female    group C
male      group D
female    group D
female    group C
female    group E
male      group A
male      group D
female    group C
male      group B
male      group C
female    group D
male      group E
male      group A
male      group A
female    group B
male      group D
male      group D
female    group C
female    group E
male      group B
female    group B
male      group D
male      group B
female    group E
male      group B
male      group C
female    group E
female    group C
male      group C
female    group B
female    group B
female    group C
male      group A
male      group E
female    group D
female    group C
female    group C
female    group C
female    group B
female    group C
female    group B
female    group D
male      group C
female    group C
female    group E
female    group D
male      group C
male      group C
male      group E
male      group D
male      group B
female    group C
female    group E
male      group D
female    group B
male      group D
female    group C
male      group D
male      group C
male      group E
female    group B
female    group B
female    group C
female    group D
male      group C
female    group B
male      group C
male      group D
male      group E
male      group E
female    group B
female    group B
male      group D
male      group C
female    group C
male      group C
male      group E
male      group B
female    group E
female    group C
male      group B
male      group B
female    group D
male      group B
female    group C
male      group D
female    group B
female    group E
female    group C
male      group D
male      group A
female    group C
male      group D
male      group C
female    group B
male      group E
male      group C
male      group D
male      group D
female    group D
male      group B
male      group C
male      group D
female    group E
female    group D
male      group E
male      group D
male      group C
male      group E
female    group B
female    group B
male      group C
male      group A
female    group D
female    group B
male      group D
male      group D
female    group E
female    group C
male      group C
female    group B
female    group C
female    group C
male      group C
female    group C
female    group E
male      group D
male      group D
female    group C
female    group D
female    group D
female    group E
male      group C
male      group C
female    group D
female    group D
male      group B
male      group C
female    group C
female    group E
female    group C
male      group B
male      group D
male      group D
female    group D
female    group D
female    group B
male      group B
male      group E
female    group B
male      group B
male      group E
male      group C
male      group D
male      group C
female    group E
male      group D
male      group B
male      group A
male      group E
male      group C
male      group D
male      group A
male      group D
female    group C
male      group B
female    group C
male      group A
male      group E
male      group C
female    group B
female    group D
female    group B
male      group B
male      group D
female    group C
female    group C
male      group C
female    group D
male      group C
male      group B
female    group D
female    group C
female    group E
female    group C
female    group C
female    group C
female    group C
male      group C
male      group A
male      group C
female    group B
male      group C
male      group C
male      group E
male      group B
female    group C
female    group B
male      group D
male      group C
female    group B
female    group D
male      group C
female    group C
female    group B
male      group D
male      group D
female    group C
male      group B
female    group C
male      group D
male      group E
female    group B
male      group E
female    group C
female    group C
female    group C
female    group B
male      group A
female    group C
male      group D
female    group D
female    group B
male      group B
female    group C
female    group D
male      group C
male      group A
male      group C
male      group C
female    group A
female    group D
male      group E
female    group C
male      group D
female    group D
female    group D
male      group E
female    group D
female    group D
female    group A
male      group A
female    group B
male      group C
male      group C
female    group E
female    group A
female    group E
female    group E
female    group C
female    group D
male      group D
male      group E
female    group D
male      group E
male      group C
female    group C
male      group A
female    group B
female    group C
male      group B
male      group D
female    group C
male      group A
female    group A
female    group D
female    group C
female    group C
male      group B
female    group B
female    group D
male      group D
female    group D
male      group E
male      group D
male      group B
female    group C
male      group E
male      group C
male      group C
male      group D
male      group E
female    group C
female    group D
female    group D
female    group A
male      group B
female    group C
male      group C
male      group C
male      group A
male      group C
male      group C
female    group C
male      group C
female    group A
male      group C
male      group C
male      group D
male      group D
male      group C
male      group D
female    group C
female    group D
female    group A
female    group B
male      group A
female    group C
male      group D
male      group C
male      group B
male      group B
female    group C
female    group E
female    group C
male      group C
female    group C
male      group C
female    group D
male      group D
female    group E
male      group B
male      group C
male      group B
female    group E
female    group C
male      group A
female    group C
female    group D
male      group A
female    group A
male      group C
female    group C
female    group C
female    group C
female    group D
female    group B
female    group D
male      group E
male      group D
female    group D
male      group E
male      group B
female    group D
male      group C
male      group A
female    group B
male      group C
male      group D
female    group C
male      group B
male      group A
female    group A
female    group C
female    group C
female    group C
female    group B
male      group D
female    group C
female    group D
female    group B
male      group E
female    group D
female    group B
male      group C
female    group E
female    group D
female    group B
male      group A
male      group B
male      group C
female    group C
male      group D
male      group A
male      group D
female    group B
female    group B
female    group C
female    group D
female    group E
female    group D
female    group B
male      group D
female    group C
male      group D
male      group C
male      group C
male      group E
male      group C
female    group C
female    group D
female    group C
female    group C
female    group C
male      group E
female    group E
male      group B
female    group C
male      group C
female    group D
male      group E
male      group A
male      group C
male      group D
female    group C
female    group D
female    group D
male      group E
female    group A
male      group C
female    group C
male      group C
male      group C
male      group B
female    group B
male      group D
male      group E
female    group C
female    group C
male      group C
female    group B
male      group D
female    group D
female    group C
male      group C
female    group D
male      group B
male      group B
female    group E
female    group D
male      group B
male      group D
male      group B
male      group A
female    group C
female    group C
female    group E
male      group A
male      group A
female    group B
female    group B
female    group D
female    group D
female    group E
female    group D
female    group D
female    group D
female    group C
female    group A
female    group C
female    group C
female    group A
male      group C
male      group A
male      group E
female    group E
female    group C
female    group C
male      group B
male      group A
female    group D
female    group D
female    group D
female    group C
female    group E
male      group D
male      group D
male      group C
female    group C
female    group C
female    group E
female    group B
male      group D
female    group C
male      group C
female    group C
female    group A
female    group C
female    group E
male      group D
male      group D
male      group C
female    group C
male      group B
male      group C
male      group A
female    group E
male      group D
male      group B
male      group D
male      group D
female    group C
male      group D
male      group B
female    group B
female    group C
male      group D
male      group A
female    group B
female    group D
male      group E
female    group D
male      group D
female    group D
female    group B
female    group E
male      group B
female    group B
female    group D
female    group E
female    group B
female    group D
male      group C
female    group A
female    group D
female    group A
female    group B
female    group B
male      group C
male      group D
female    group D
male      group D
male      group C
male      group C
female    group D
female    group C
male      group D
female    group C
female    group C
female    group B
male      group C
male      group D
female    group C
male      group D
female    group C
female    group C
female    group D
female    group B
female    group E
female    group C
male      group D
male      group D
female    group D
male      group B
male      group B
female    group C
male      group B
female    group E
male      group E
male      group D
male      group A
male      group E
female    group C
female    group E
female    group C
female    group D
female    group C
female    group D
female    group C
female    group A
female    group D
male      group C
female    group E
female    group B
male      group A
female    group D
female    group B
male      group A
male      group D
male      group C
male      group D
female    group D
male      group C
female    group E
female    group D
male      group D
female    group B
female    group B
male      group C
female    group C
female    group C
male      group E
female    group C
male      group D
female    group B
male      group C
male      group B
male      group E
female    group E
male      group E
female    group D
male      group C
female    group B
male      group A
female    group C
male      group D
female    group E
male      group C
male      group C
female    group B
male      group D
male      group C
male      group D
female    group A
female    group C
female    group C
male      group B
male      group D
male      group D
male      group C
female    group C
male      group B
male      group D
male      group E
male      group C
female    group C
male      group C
female    group E
male      group D
male      group E
female    group D
male      group B
female    group C
female    group D
male      group D
female    group B
male      group D
female    group B
female    group C
male      group B
female    group D
male      group A
male      group B
male      group D
female    group B
female    group C
male      group B
female    group B
female    group B
female    group C
female    group A
male      group E
female    group D
female    group B
female    group B
female    group C
male      group C
female    group B
female    group E
female    group B
male      group C
female    group C
female    group B
female    group D
male      group D
male      group E
female    group B
female    group E
male      group D
female    group E
male      group E
female    group C
male      group C
male      group C
female    group E
female    group B
female    group C
male      group A
female    group D
female    group E
male      group C
male      group B
male      group A
male      group A
female    group C
male      group E
female    group C
male      group B
female    group A
male      group D
female    group B
female    group C
female    group A
female    group D
male      group E
female    group B
female    group C
male      group C
female    group C
female    group C
female    group D
male      group B
female    group A
female    group C
male      group A
female    group B
male      group B
female    group C
male      group E
female    group A
male      group B
female    group C
female    group D
male      group C
female    group B
male      group B
female    group D
male      group E
male      group C
male      group D
female    group C
male      group D
male      group C
female    group A
female    group E
male      group E
male      group C
female    group B
male      group B
female    group C
male      group B
male      group C
female    group C
female    group E
male      group D
female    group C
male      group C
male      group D
male      group C
male      group B
male      group E
male      group C
male      group B
female    group C
male      group B
male      group E
female    group C
male      group C
male      group D
male      group C
female    group D
female    group D
male      group C
female    group E
female    group B
male      group D
female    group E
female    group C
female    group E
male      group C
female    group D
male      group D
female    group E
female    group E
female    group A
male      group D
female    group E
female    group E
male      group B
female    group B
male      group D
female    group D
male      group D
female    group C
female    group A
female    group D
female    group D
male      group D
male      group B
female    group D
female    group C
male      group E
male      group D
female    group A
female    group C
female    group C
female    group B
female    group E
male      group E
female    group C
female    group C
male      group B
male      group D
female    group C
male      group D
female    group B
male      group D
male      group E
male      group E
female    group D
male      group E
female    group C
male      group C
male      group D
male      group D
male      group C
male      group C
male      group D
male      group A
female    group E
male      group D
male      group D
male      group C
female    group D
male      group C
male      group A
female    group B
female    group C
male      group B
female    group D
male      group B
female    group E
male      group E
female    group D
female    group E
male      group C
female    group C
male      group E
male      group C
female    group D
female    group D
male      group C
female    group A
female    group D
female    group E
female    group C
male      group D
female    group D
male      group A
male      group C
female    group E
female    group B
female    group D
male      group C
female    group A
female    group D
female    group A
female    group C
male      group B
male      group C
male      group D
female    group C
female    group B
male      group D
male      group B
female    group A
female    group C
male      group A
female    group C
male      group E
female    group A
female    group D
male      group E
female    group B
female    group D
female    group D
male      group A
female    group E
male      group C
female    group C
female    group D
female    group D

In [44]:
print(data[["gender", "race/ethnicity", "lunch"]])

KeyError: "['gender'] not in index"

In [45]:
# Selection by row

print(data.loc[0])

KeyError: 0

In [48]:
print(data.loc["male"]) #after index_col in data importing

       race/ethnicity parental level of education         lunch  \
gender
male          group A          associate's degree  free/reduced
male          group C                some college      standard
male          group B                some college  free/reduced
male          group D                 high school  free/reduced
male          group C          associate's degree      standard
...               ...                         ...           ...
male          group A                 high school      standard
male          group E            some high school      standard
male          group E                 high school  free/reduced
male          group A                 high school      standard
male          group C                 high school  free/reduced

       test preparation course  math score  reading score  writing score
gender
male                      none          47             57             44
male                      none          76             78             75
male                      none          40             43             39
male                 completed          64             64             67
male                      none          58             54             52
...                        ...         ...            ...            ...
male                      none          57             51             54
male                 completed          81             75             76
male                 completed          86             81             75
male                      none          63             63             62
male                      none          62             55             55

[482 rows x 7 columns]

In [52]:
print(data.loc["male", ["race/ethnicity", "math score"]])

       race/ethnicity  math score
gender
male          group A          47
male          group C          76
male          group B          40
male          group D          64
male          group C          58
...               ...         ...
male          group A          57
male          group E          81
male          group E          86
male          group A          63
male          group C          62

[482 rows x 2 columns]

In [58]:
# Exersize

ploe = input("Parantel level of education: ")

try:
    print(data.loc[ploe])
except KeyError:
    print(f"ploe {ploe} not found")

Parantel level of education: some college
ploe some college not found

Filtering

In [60]:
new_data = data.loc[data["math score"] > 60]
new_data.head()

,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
gender,,,,,,,
female,group B,bachelor's degree,standard,none,72,72,74
female,group C,some college,standard,completed,69,90,88
female,group B,master's degree,standard,none,90,95,93
male,group C,some college,standard,none,76,78,75
female,group B,associate's degree,standard,none,71,83,78

Aggregation

reduce a set of values into a single summary value used to summarize and analyze data often used with the groupby() function

In [62]:
print(data.mean(numeric_only=True))

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [64]:
print(data.min(numeric_only=True))

math score        0
reading score    17
writing score    10
dtype: int64

In [65]:
print(data.max(numeric_only=True))

math score       100
reading score    100
writing score    100
dtype: int64

In [67]:
print(data.count())

race/ethnicity                 1000
parental level of education    1000
lunch                          1000
test preparation course        1000
math score                     1000
reading score                  1000
writing score                  1000
dtype: int64

In [68]:
# the above functions where for entire dataframe
# the next ones will be for specific calumns

In [69]:
group = data.groupby("race/ethnicity")

In [70]:
print(group["math score"].mean())

race/ethnicity
group A    61.629213
group B    63.452632
group C    64.463950
group D    67.362595
group E    73.821429
Name: math score, dtype: float64

Data Cleaning

In [71]:
data = data.drop(columns = ["lunch"])

In [73]:
data.columns

Index(['race/ethnicity', 'parental level of education',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [75]:
data = data.dropna(subset=["test preparation course"]) # drop not availabvle the rows in the caulmns

In [76]:
data = data.fillna({"test preparation course" : "None"})

In [77]:
#fix inconsistent values
data["race/ethnicity"] = data["race/ethnicity"].replace({"group A" : "group_a"})